cc_binary(
    name='socket_server',
    srcs=[
        'socket_server.cc',
    ],
    # deps=[
    #     '//thirdparty/coost:co',
    # ]
)

cc_binary(
    name='socket_client',
    srcs=[
        'socket_client.cc',
    ],
)

cc_binary(
    name='nonsocket_client',
    srcs=[
        'nonsocket_client.cc',
    ],
)
