all:
	g++ sender_3.cc -o send3
	g++ sender_5.cc -o send5
	g++ sender_3_5.cc -o send35
	g++ receiver_3.cc -o recv3
	g++ receiver_5.cc -o recv5
	g++ receiver_3_5.cc -o recv35

clean:
	rm send3 send5 send35 recv3 recv5 recv35
